export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";
export const FETCH_INDIVIDUAL_PRODUCT = "FETCH_INDIVIDUAL_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
